import os.path
import glob

Import( 'env opts incdir libdir topdir libs ' )

print "----- Building TNoddy codes -----"

# Testing codes

env.Program( 'Test/Matrix_test.out' , ['Test/Matrix_test.cpp'] , OPTS = opts, LIBS = libs)  #Matrix
env.Program( 'Test/Vector_test.out' , ['Test/Vector_test.cpp'] , OPTS = opts, LIBS = libs)  #Vector
env.Program( 'Test/LinSys_test.out' , ['Test/LinSys_test.cpp'] , OPTS = opts, LIBS = libs)  #Linear system
env.Program( 'Test/Sparse_test.out' , ['Test/Sparse_test.cpp'] , OPTS = opts, LIBS = libs)  #SparseMatrix


# Project codes

#env.Program( 'Project/Base_Flow_Transpiration.out' , ['Project/Base_Flow_Transpiration.cpp'] , OPTS = opts, LIBS = libs )
#env.Program( 'Project/Eigenvalue_Problem.out' , ['Project/Eigenvalue_Problem.cpp'] , OPTS = opts, LIBS = libs )
